#ifndef HOWZAT_FFI_H
#define HOWZAT_FFI_H

#pragma once

/* Warning: this file is autogenerated. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <gmp.h>

typedef enum howzat_representation_t {
  HOWZAT_REPR_EUCLIDEAN_VERTICES = 0,
  HOWZAT_REPR_INEQUALITY = 1,
  HOWZAT_REPR_HOMOGENEOUS_GENERATORS = 2,
} howzat_representation_t;

typedef enum howzat_coeff_kind_t {
  HOWZAT_COEFF_F64 = 0,
  HOWZAT_COEFF_GMPRAT = 1,
} howzat_coeff_kind_t;

typedef enum howzat_graph_kind_t {
  HOWZAT_GRAPH_DENSE = 0,
  HOWZAT_GRAPH_SPARSE = 1,
} howzat_graph_kind_t;

typedef struct howzat_adjacency_list_t howzat_adjacency_list_t;

typedef struct howzat_backend_t howzat_backend_t;

typedef struct howzat_dense_graph_t howzat_dense_graph_t;

typedef struct howzat_result_t howzat_result_t;

typedef struct howzat_error_t {
  char *message;
} howzat_error_t;

typedef struct howzat_f64_slice_t {
  const double *ptr;
  uintptr_t len;
} howzat_f64_slice_t;

typedef struct howzat_i64_slice_t {
  const int64_t *ptr;
  uintptr_t len;
} howzat_i64_slice_t;

typedef struct howzat_mpq_slice_t {
  const mpq_srcptr *ptr;
  uintptr_t len;
} howzat_mpq_slice_t;

typedef struct howzat_str_slice_t {
  const char *const *ptr;
  uintptr_t len;
} howzat_str_slice_t;

typedef struct howzat_usize_slice_t {
  const uintptr_t *ptr;
  uintptr_t len;
} howzat_usize_slice_t;

const char *howzat_error_message(const struct howzat_error_t *err);

void howzat_error_free(struct howzat_error_t *err);

struct howzat_backend_t *howzat_backend_new(const char *spec, struct howzat_error_t **out_err);

void howzat_backend_free(struct howzat_backend_t *backend);

const char *howzat_backend_spec(const struct howzat_backend_t *backend);

struct howzat_result_t *howzat_solve(const double *data,
                                     uintptr_t rows,
                                     uintptr_t cols,
                                     enum howzat_representation_t repr,
                                     struct howzat_error_t **out_err);

struct howzat_result_t *howzat_solve_exact(const int64_t *data,
                                           uintptr_t rows,
                                           uintptr_t cols,
                                           enum howzat_representation_t repr,
                                           struct howzat_error_t **out_err);

struct howzat_result_t *howzat_solve_exact_gmprat(const mpq_srcptr *data,
                                                  uintptr_t rows,
                                                  uintptr_t cols,
                                                  enum howzat_representation_t repr,
                                                  struct howzat_error_t **out_err);

struct howzat_result_t *howzat_backend_solve(const struct howzat_backend_t *backend,
                                             const double *data,
                                             uintptr_t rows,
                                             uintptr_t cols,
                                             enum howzat_representation_t repr,
                                             struct howzat_error_t **out_err);

struct howzat_result_t *howzat_backend_solve_exact(const struct howzat_backend_t *backend,
                                                   const int64_t *data,
                                                   uintptr_t rows,
                                                   uintptr_t cols,
                                                   enum howzat_representation_t repr,
                                                   struct howzat_error_t **out_err);

struct howzat_result_t *howzat_backend_solve_exact_gmprat(const struct howzat_backend_t *backend,
                                                          const mpq_srcptr *data,
                                                          uintptr_t rows,
                                                          uintptr_t cols,
                                                          enum howzat_representation_t repr,
                                                          struct howzat_error_t **out_err);

void howzat_result_free(struct howzat_result_t *result);

const char *howzat_result_spec(const struct howzat_result_t *result);

uintptr_t howzat_result_dimension(const struct howzat_result_t *result);

uintptr_t howzat_result_vertices(const struct howzat_result_t *result);

uintptr_t howzat_result_facets(const struct howzat_result_t *result);

uintptr_t howzat_result_ridges(const struct howzat_result_t *result);

double howzat_result_total_seconds(const struct howzat_result_t *result);

uintptr_t howzat_result_fails(const struct howzat_result_t *result);

uintptr_t howzat_result_fallbacks(const struct howzat_result_t *result);

enum howzat_coeff_kind_t howzat_result_coeff_kind(const struct howzat_result_t *result);

void howzat_result_generators_shape(const struct howzat_result_t *result,
                                    uintptr_t *out_rows,
                                    uintptr_t *out_cols);

void howzat_result_inequalities_shape(const struct howzat_result_t *result,
                                      uintptr_t *out_rows,
                                      uintptr_t *out_cols);

struct howzat_f64_slice_t howzat_result_generators_f64(const struct howzat_result_t *result);

struct howzat_f64_slice_t howzat_result_inequalities_f64(const struct howzat_result_t *result);

struct howzat_i64_slice_t howzat_result_generators_i64(const struct howzat_result_t *result);

struct howzat_i64_slice_t howzat_result_inequalities_i64(const struct howzat_result_t *result);

struct howzat_mpq_slice_t howzat_result_generators_gmprat(const struct howzat_result_t *result);

struct howzat_mpq_slice_t howzat_result_inequalities_gmprat(const struct howzat_result_t *result);

struct howzat_str_slice_t howzat_result_generators_str(const struct howzat_result_t *result);

struct howzat_str_slice_t howzat_result_inequalities_str(const struct howzat_result_t *result);

struct howzat_f64_slice_t howzat_result_vertex_positions(const struct howzat_result_t *result);

void howzat_result_vertex_positions_shape(const struct howzat_result_t *result,
                                          uintptr_t *out_vertex_count,
                                          uintptr_t *out_dim);

struct howzat_usize_slice_t howzat_result_facets_to_vertices_offsets(const struct howzat_result_t *result);

struct howzat_usize_slice_t howzat_result_facets_to_vertices_data(const struct howzat_result_t *result);

enum howzat_graph_kind_t howzat_result_vertex_adjacency_kind(const struct howzat_result_t *result);

enum howzat_graph_kind_t howzat_result_facet_adjacency_kind(const struct howzat_result_t *result);

const struct howzat_dense_graph_t *howzat_result_vertex_adjacency_dense(const struct howzat_result_t *result);

const struct howzat_adjacency_list_t *howzat_result_vertex_adjacency_sparse(const struct howzat_result_t *result);

const struct howzat_dense_graph_t *howzat_result_facet_adjacency_dense(const struct howzat_result_t *result);

const struct howzat_adjacency_list_t *howzat_result_facet_adjacency_sparse(const struct howzat_result_t *result);

uintptr_t howzat_dense_graph_node_count(const struct howzat_dense_graph_t *graph);

uintptr_t howzat_dense_graph_degree(const struct howzat_dense_graph_t *graph, uintptr_t node);

bool howzat_dense_graph_contains(const struct howzat_dense_graph_t *graph,
                                 uintptr_t node,
                                 uintptr_t neighbor);

uintptr_t howzat_dense_graph_neighbors(const struct howzat_dense_graph_t *graph,
                                       uintptr_t node,
                                       uintptr_t *out,
                                       uintptr_t out_cap);

uintptr_t howzat_adjacency_list_node_count(const struct howzat_adjacency_list_t *graph);

uintptr_t howzat_adjacency_list_degree(const struct howzat_adjacency_list_t *graph, uintptr_t node);

bool howzat_adjacency_list_contains(const struct howzat_adjacency_list_t *graph,
                                    uintptr_t node,
                                    uintptr_t neighbor);

struct howzat_usize_slice_t howzat_adjacency_list_neighbors(const struct howzat_adjacency_list_t *graph,
                                                            uintptr_t node);

#endif  /* HOWZAT_FFI_H */
